# Generated by Django 4.2.2 on 2023-07-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
