# Generated by Django 4.2.2 on 2023-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary'),
        ),
    ]
