# Generated by Django 4.2.2 on 2023-07-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
